### ISSUE TITLE
Enhance existing home page

### ISSUE THREAD

**Issue by KaizenGirl1111** [KaizenGirl1111/GSGrihSangini#10]
The existing home page of the site is plain. If you have worked well in CSS, you are free to enhance the professionalism and aesthetics of this page.

**Comment by ashvin804** [comment]
can you assign this task to me.

**Comment by Aditya3403** [comment]
I would like to work on this issue .Kindly assign it to me.

**Comment by KaizenGirl1111** [comment]
assigned to @sulogna2001 for now, @Aditya3403 you can take over if she needs help :0

**Comment by thefstalphabet** [comment]
Hey @KaizenGirl1111, I would like to work on this issue, under GSSoC'22. Can you please assign it to me?

**Comment by sulogna2001** [comment]
@KaizenGirl1111 I am working on it

**Comment by KaizenGirl1111** [comment]
@sulogna2001 any update?

**Comment by mayank-del** [comment]
@KaizenGirl1111 , u should assign this issue to me, I should also get a chance to work on it
