### ISSUE TITLE
Setting up JWT authentication for the worker 

### ISSUE THREAD

**Issue by ayush25102001** [KaizenGirl1111/GSGrihSangini#142]
Can I set up JWT authentication for worker
Participant under Gssoc'22

**Comment by ayush25102001** [comment]
> Can I set up JWT authentication for worker, here I will handle both the frontend and the backend part.
Participant under Gssoc'22

**Comment by KaizenGirl1111** [comment]
Hello @ayush25102001 !
Thank you for being a consistent Contributor to our project!
Also congratulations on being one of the  top Contributor of GSSoC, indeed a huge acheivement
Here is a opportunity I believe you deserve -
https://digitalproductschool.io/apply/ 
Apply for Digital Product School
Deadline for September cohort - 30

Other opportunities I believe you can crack- MLH, GSoC
