### ISSUE TITLE
!!! Project isn't working !!!

### ISSUE THREAD

**Issue by Siddhesh777** [KaizenGirl1111/GSGrihSangini#153]
There are some errors in the project. The project is not starting.
I would like to fix those issues.

I am Contributor at GSSOC'22.
Please assign this issue to me.

**Comment by Siddhesh777** [comment]
@KaizenGirl1111

**Comment by KaizenGirl1111** [comment]
Hi @Siddhesh777 , I had uncommitted some previous commits made by other contributors 
Is this issue still persisting? Or is it resolved so you closed it?

**Comment by Siddhesh777** [comment]
@KaizenGirl1111 I have fixed all the issues.
The project is working absolutely fine now 
😁
