### ISSUE TITLE
GrihSangini SoS 

### ISSUE THREAD

**Issue by KaizenGirl1111** [KaizenGirl1111/GSGrihSangini#161]
A page called GrihSangini SoS for emergency service deliveries under 2 hours. Eg. Emergency car repairing.

Right now, just build the frontend of this page.

The web page should be connected to the navbar. 

Format of this page-

<relevant image eg. Image of lady worker>
<GrihSangini SoS button>
<description of SoS services- We delivery service like emergency car repairing, emergency maid service in 2 hours in your vicinity. Terms and conditions applied>

This issue will be alloted to someone who can design a webpage aesthetically. :)

**Comment by Siddhesh777** [comment]
I would like to work on this issue @KaizenGirl1111

**Comment by Siddhesh777** [comment]
@KaizenGirl1111 
What data are we supposed to take as input in this page?

**Comment by Siddhesh777** [comment]
Name, work category, address, contact no, anything else ?
