### ISSUE TITLE
ContactUs

### ISSUE THREAD

**Issue by ayush25102001** [KaizenGirl1111/GSGrihSangini#25]
When the user selects contact-us from the header nothing is displayed can I create a contact us component(form) that gets rendered when contact-us is selected in the header.

**Comment by ayush25102001** [comment]
@KaizenGirl1111

**Comment by KaizenGirl1111** [comment]
Yes sure 
Our email is gsgrihsangini.com 
So you direct the user to email us

**Comment by KaizenGirl1111** [comment]
gsgrihsangini@gmail.com @ayush25102001

**Comment by KaizenGirl1111** [comment]
this PR was merged right? @ayush25102001

**Comment by ayush25102001** [comment]
> this PR was merged right? @ayush25102001

Yes mam
