### ISSUE TITLE
SignUp Form UI

### ISSUE THREAD

**Issue by ayush25102001** [KaizenGirl1111/GSGrihSangini#26]
Can I improve the UI of the signUp form.

**Comment by ayush25102001** [comment]
@KaizenGirl1111

**Comment by KaizenGirl1111** [comment]
Sure  
If you feel that the sign up form needs enhancement 
You can choose to work on it
I'll assign it to you once you confirm

**Comment by KaizenGirl1111** [comment]
this PR was merged? @ayush25102001

**Comment by ayush25102001** [comment]
> this PR was merged? @ayush25102001

Yes mam
