### ISSUE TITLE
Confirm password field in signup page.

### ISSUE THREAD

**Issue by Siddhesh777** [KaizenGirl1111/GSGrihSangini#30]
It is normal convention that whenever the user is registering, then there should be two fields namely `Password` and `Confirm Password` and if both of them matches then only user can register himself.We also have to maintain the state of both of the fields.
This is used to ensure that the user don't make any typo.

I am contributor at gssoc'22.
Please assign this issue to me.

**Comment by KaizenGirl1111** [comment]
go ahead!
