### ISSUE TITLE
Github Pages not working 

### ISSUE THREAD

**Issue by KaizenGirl1111** [KaizenGirl1111/GSGrihSangini#34]
_Hey contributors! This is a good first issue. Or if you're tired making advanced commits, here's an easy issue to give you solace._

The Github Pages is active but not working
If you're able to host from your side, just make a pr to the read.me and append the link of the site on the read.me

**Comment by gurjeetsinghvirdee** [comment]
Hey @KaizenGirl1111 assign me

**Comment by KaizenGirl1111** [comment]
@gurjeetsinghvirdee you may start working on it
Sorry had some tests going on, so responded late
