### ISSUE TITLE
UI improvement of login/signup page

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [KaizenGirl1111/GSGrihSangini#60]
**Is your feature request related to a problem? Please describe.**
UI of the login page, sign page worker login, etc.. look so odd

**Describe the solution you'd like**
UI enhancement

**Comment by gurjeetsinghvirdee** [comment]
@KaizenGirl1111 @moulikagrawal assign me

**Comment by KaizenGirl1111** [comment]
Great
