### ISSUE TITLE
Worker login

### ISSUE THREAD

**Issue by ayush25102001** [KaizenGirl1111/GSGrihSangini#61]
Mam can I also add mobile no field in login-worker form.I have also added it to the schema in the backend.Actually login with only password field would create problem if 2 or more people set the same password.
Participant under Gssoc’22

**Comment by ayush25102001** [comment]
![Screenshot (137)](https://user-images.githubusercontent.com/78008646/166814927-2c9dce01-07c7-4712-ba62-985790d86ce0.png)

**Comment by KaizenGirl1111** [comment]
Did merge your PR @ayush25102001
