### ISSUE TITLE
Create Contact us page

### ISSUE THREAD

**Issue by Siddhesh777** [KaizenGirl1111/GSGrihSangini#62]
**Is your feature request related to a problem? Please describe.**
There is no contact us page right now, instead when user click on [contact us](url) button, the user is taken directly to email.
I want to design a Contact us page for this project

**Additional context**
I am contributor at gssoc'22.
Please assign this issue to me.

**Comment by KaizenGirl1111** [comment]
Assigned @Siddhesh777
