### ISSUE TITLE
Remove options from navbar

### ISSUE THREAD

**Issue by ayush25102001** [KaizenGirl1111/GSGrihSangini#65]
Currently the Navbar is looking quite clumsy due to so many options where the first 3 , Aboutus ,Services Reviews are non functional so can I remove them and rearrange the existing options
Participant under gssoc'22

**Comment by ayush25102001** [comment]
![Screenshot (138)](https://user-images.githubusercontent.com/78008646/166816214-9a64ce76-0a34-43ba-8b25-8e62fd396657.png)

Looks a lot cleaner now.

**Comment by KaizenGirl1111** [comment]
@ayush25102001 sounds really interesting 
Could you please share how are you planning to rearrange the navbar items?
