### ISSUE TITLE
Want to Setup Google Authentication 

### ISSUE THREAD

**Issue by Abh1shekSingh** [KaizenGirl1111/GSGrihSangini#97]
**Is your feature request related to a problem? Please describe.**

Want to add Google Authentication

@KaizenGirl1111 Please assign the task to me

**Comment by mayank-del** [comment]
@KaizenGirl1111 , can I work under this issue under gssoc22

**Comment by KaizenGirl1111** [comment]
@Abh1shekSingh ok

**Comment by Abh1shekSingh** [comment]
@KaizenGirl1111 I want to ask something before getting started. is Email Auth and other authentication working fine or not. If they are not working fine then I can authenticate those things also. I have checked, but cant really say if they are working or nt. So please tell me
